spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demo
    hikari:
      maximum-pool-size: 20
    properties:
      hibernate:
        generate_statistics: true


management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

